// Types shared by the Operations approval flow. Every sensitive action must be
// expressed as an OpRequest and routed through the drawer.

export const OP_KINDS = [
  "operator-start",
  "operator-stop",
  "operator-restart",
  "operator-restore",
  "operator-register",
  "operator-display",
  "operator-seal-key",
  "chat-bootstrap-peers",
  "cluster-name-register",
  "rotate-keys",
  "redelegate",
  "export-backup",
  "cluster-swap",
  "cluster-accept-invite",
  "cluster-form",
  "cluster-update-charter",
  "cluster-request-join",
  "cluster-vote-admit",
  "cluster-resign",
  "freeze-admission",
  "emergency-key-rotation",
  "ota-apply",
  "ota-rollback",
  "operator-reprovision",
] as const;

export type OpKind = (typeof OP_KINDS)[number];

// Inputs the register form collects from the operator. Lives on
// OpRequest as `registerInput` so the OpsContext branch can pass them
// to the SDK helper without re-parsing the `fields[]` display rows.
export type RegisterInput = {
  endpoint: string;
  capabilities: number;
  bondLythoshi: string;
  peerIdHex?: string;
  sppkHashHex?: string;
};

// Inputs the redelegate form collects from the operator. These map
// directly to the delegation precompile's
// `redelegate(uint32,uint32,uint16)` calldata.
export type RedelegateInput = {
  fromCluster: number;
  toCluster: number;
  weightBps: number;
};

// Inputs the restore form collects from the operator/foundation runbook. The
// peer id is the node-registry key passed to recoverOperatorNode(bytes32).
export type RestoreInput = {
  peerIdHex: string;
};

// Inputs for node-registry `setChatBootstrapPeers(bytes32,bytes)`.
// The peer id selects the operator-owned registration row, while `peers`
// is a comma/newline/whitespace separated libp2p multiaddr list.
export type ChatBootstrapPeersInput = {
  peerIdHex: string;
  peers: string;
};

// Inputs for node-registry `setOperatorDisplay(bytes32,string,string)`.
// The peer id selects the operator-owned registration row; empty text clears
// the corresponding public display field.
export type OperatorDisplayInput = {
  peerIdHex: string;
  moniker: string;
  alias: string;
};

// Inputs for node-registry `publishOperatorSealKey(bytes32,bytes)`.
// The EK is the public ML-KEM-768 encapsulation key generated by Monarch OS.
export type OperatorSealKeyInput = {
  peerIdHex: string;
  sealEkHex: string;
};

// Inputs for cluster-name-registry `register(string,uint64)`.
// The tx must be signed by the cluster's primary anchor key.
export type ClusterNameInput = {
  clusterId: string;
  name: string;
};

// Inputs for node-registry `submitPendingChange(uint8,bytes,uint64,uint64)`.
// Desktop currently surfaces Add for cluster invites and Rotate for cluster
// swaps; Remove is kept in the type because the ABI discriminant is stable.
export type PendingChangeInput = {
  kind: "add" | "remove" | "rotate";
  targetPubkeyHex: string;
  effectiveEpoch: string;
  intentId: string;
};

// Inputs for CJ-1 self-service cluster admission. `requestClusterJoin`
// is signed by the joining operator and sends the bond as tx value once
// the runtime precompile is live.
export type ClusterJoinRequestInput = {
  clusterId: string;
  operatorPubkeyHex: string;
  bondLythoshi: string;
};

// Inputs for CJ-1 cluster-member admission votes. The chain tallies
// votes by the current cluster roster and admits once policy threshold is met.
export type ClusterVoteAdmitInput = {
  clusterId: string;
  operatorIdHex: string;
  voterPubkeyHex: string;
};

// Inputs for the self-service `formCluster(bytes,bytes,bytes)` call.
// Signatures are ten ML-DSA-65 consent signatures over the canonical
// roster digest, in roster order: seven active first, then three standby.
// When `charterHex` (the 30-byte V2 economics charter) is present the
// executor encodes `formCluster(bytes,bytes,bytes,bytes)` and the ten
// signatures must verify over the charter-committing V2 digest; absent,
// the V1 flow stays byte-identical.
export type ClusterFormInput = {
  activePubkeysHex: string;
  standbyPubkeysHex: string;
  signaturesHex: string;
  charterHex?: string;
};

// Inputs for the live-cluster `updateCharter(uint32,bytes,bytes,bytes)`
// amendment (Component H). `charterHex` is the proposed 30-byte charter;
// `signerPubkeysHex` / `signaturesHex` are the ≥7 active-member ML-DSA-65
// consent pubkeys + signatures over the updateCharter consent digest (1:1,
// signer order). The executor encodes the calldata and submits from the
// caller's operator key; the chain enforces the 7-of-10 active-member
// threshold and applies the new terms only after the cooldown.
export type ClusterUpdateCharterInput = {
  clusterId: string;
  charterHex: string;
  signerPubkeysHex: string[];
  signaturesHex: string[];
};

// Inputs for the Q120 voluntary cluster resignation
// (`Tx::ClusterResignation`). The resigning operator signs the native
// frame with the PQM-1-derived ML-DSA-65 consensus key; the runtime
// resolves the cluster from on-chain membership, so `clusterId` is a
// display-only context field and is NOT part of the signed payload.
// `nonce` is the operator-local resignation nonce (strictly greater than
// the last accepted one). `expedite` requests a foundation expedite; the
// executor still enforces the actual authority.
export type ClusterResignationInput = {
  clusterId: string;
  nonce: string;
  expedite: boolean;
};

// Inputs for the operator-callable `attestDkgReshare(uint64,bytes,bytes)`.
export type DkgReshareAttestationInput = {
  intentId: string;
  consensusPublicKeysHex: string;
  thresholdSigHex: string;
};

export type FreezeAdmissionInput = {
  reasonHashHex: string;
};

export type EmergencyKeyRotationInput = {
  targetPubkeyHex: string;
  effectiveEpoch: string;
  intentId: string;
};

export type OtaRebootMode = "default" | "powercycle";

// Inputs for the Talos Upgrade RPC. `preserve=true` is enforced by the
// Rust bridge so `/var/lib/protocore` survives the image replacement.
export type OtaApplyInput = {
  image: string;
  stage: boolean;
  rebootMode: OtaRebootMode;
};

export type OpStage = "preview" | "auth" | "executing" | "done" | "error";

export type OpField = { key: string; label: string; value: string };

export type OpRequest = {
  kind: OpKind;
  title: string;
  sub: string;
  intro: string;
  /** Optional spec-level prose (selectors, byte sizes, precompile
   *  addresses) demoted out of `intro` into an expandable
   *  "technical details" block in the drawer. */
  technical?: string;
  fields: OpField[];
  icon?: string;
  risk?: "low" | "medium" | "high";
  effects?: string[];
  diff?: OpField[];
  needsPasskey?: boolean;
  destructive?: boolean;
  confirmLabel?: string;
  /** Present only when `kind === "operator-register"`. Carries the
   *  parsed form inputs the SDK helper needs to build + submit the
   *  register tx. Lives on OpRequest so the OpsContext branch stays
   *  shape-pure and the form component owns validation. */
  registerInput?: RegisterInput;
  /** Present only when `kind === "redelegate"`. Carries the parsed
   *  delegation precompile arguments for the signed tx path. */
  redelegateInput?: RedelegateInput;
  /** Present only when `kind === "operator-restore"`. Carries the
   *  node-registry peer id recovered by the recovery executor. */
  restoreInput?: RestoreInput;
  /** Present only when `kind === "chat-bootstrap-peers"`. Carries the
   *  operator-owned chat bootstrap metadata declaration. */
  chatBootstrapPeersInput?: ChatBootstrapPeersInput;
  /** Present only when `kind === "operator-display"`. Carries public
   *  operator display metadata. */
  operatorDisplayInput?: OperatorDisplayInput;
  /** Present only when `kind === "operator-seal-key"`. Carries the
   *  operator's public LythiumSeal encapsulation key. */
  operatorSealKeyInput?: OperatorSealKeyInput;
  /** Present only when `kind === "cluster-name-register"`. */
  clusterNameInput?: ClusterNameInput;
  /** Present only when `kind` maps to a foundation pending-change op. */
  pendingChangeInput?: PendingChangeInput;
  /** Present only when `kind === "cluster-request-join"`. */
  clusterJoinRequestInput?: ClusterJoinRequestInput;
  /** Present only when `kind === "cluster-vote-admit"`. */
  clusterVoteAdmitInput?: ClusterVoteAdmitInput;
  /** Present only when `kind === "cluster-resign"`. Carries the
   *  operator-local resignation nonce and the foundation-expedite flag. */
  clusterResignationInput?: ClusterResignationInput;
  /** Present only when `kind === "cluster-form"`. */
  clusterFormInput?: ClusterFormInput;
  /** Present only when `kind === "cluster-update-charter"`. Carries the
   *  proposed 30-byte charter + the collected active-member consents. */
  clusterUpdateCharterInput?: ClusterUpdateCharterInput;
  /** Present only when `kind === "rotate-keys"`. Carries the DKG re-share
   *  attestation payload produced by the external ceremony. */
  dkgReshareInput?: DkgReshareAttestationInput;
  /** Present only when `kind === "freeze-admission"`. */
  freezeAdmissionInput?: FreezeAdmissionInput;
  /** Present only when `kind === "emergency-key-rotation"`. */
  emergencyKeyRotationInput?: EmergencyKeyRotationInput;
  /** Present only when `kind === "ota-apply"`. Carries the Talos image
   *  reference and non-secret upgrade switches. */
  otaApplyInput?: OtaApplyInput;
};

export type OpResult = {
  ok: boolean;
  message: string;
  txHash?: string;
  receiptId?: string;
};
